FROM node:20-alpine

# Install recommended packages https://github.com/vercel/next.js/tree/canary/examples/with-docker.
RUN apk add --no-cache libc6-compat

# Enable Corepack for Yarn
RUN corepack enable
