FROM node:20-alpine

# Install recommended packages https://docs.strapi.io/dev-docs/installation/docker.
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev git curl

# Enable Corepack for Yarn
RUN corepack enable
